### ISSUE TITLE
Having a created at column? 

### ISSUE THREAD

**Issue by Crash--** [cozy/cozy-drive#1094]
I just synchronized all the stuff stored on my phone... (Well I've not finished yet...) 

On Cozy Cloud, I've an "updated" ("Mise à jour") column.  This column is filled with the current date of synchronization (yesterday or today). 

Is there a way to have the real created date? Because having 3 or 4 years files and can't sort them by date it's something problematic.

**Comment by y-lohse** [comment]
Hi, and thanks for the feedback! Right now there's no way to see that date in the web or mobile UI, but it should be properly synchronized and available through cozy-desktop for example.  
We've noted your request though and we'll update you here if/when we have something planned around that (right now half the team is on holiday so it might take a while  ¯\_(ツ)_/¯).

I'll close the issue because we're using it to track technical issues more than feature requests, but feel free to reply in here.
