### ISSUE TITLE
View the folder or file being accessed during the scan

### ISSUE THREAD

**Issue by louisgrasset** [cozy/cozy-drive#1170]

**Comment by Crash--** [comment]
Hi @louisgrasset, 

Can you describe a bit more what you think?

**Comment by D219** [comment]
Not the original asker, but I think the problem is that when asking for a automatic media backup (which is one of the main point of using the app), the user have no indication or clue about which folders are scanned and backuped.
Is it the DCIM folder? Part of it? The Pictures folder? Are subfolders synced too? Is it the ones on the Internal Storage? The SD Card? Both?
Actually, I do have the same problem, the app is telling me it scanned everything and is synced up, but not a single photo was sent to the server, and there is no way to tell the app to check a specific folder.

A first step could be a simple information line "Backuped folders: " followed by a list of paths checked by the media backup, in the app (On the settings, in the Media Backup section?) would help the average user know if the problem come from non-standard folders on their phones. 

Even better, a way to select different folders for backup would be wonderful, but would ask for a lot more work.

**Comment by Crash--** [comment]
Thank you @D219 for the explanations! 

If I'm not mistaken, on Android we use the [Android MediaStore](https://developer.android.com/reference/android/provider/MediaStore) to get Images & Videos references (https://github.com/cozy/cordova-plugin-list-library-items/blob/c1ff1f0f46b512a19394229b51b8149b67c4a16e/src/android/io/cozy/plugins/listlibraryitems/ListLibraryItems.java#L177). The idea of MediaStore is to avoid problems with non-standard folders as all medias are referenced in it. 

So 2 hypothesis : 
- Our usage of MediaStore is wrong 
- Your device do not store anything in `MediaStore`. Can you give me more details about your phone?

**Comment by D219** [comment]
@Crash-- That explain why you were confused by the title, if everything is abstracted.

For my specific phone, it is a Sony XPeria XZ (Model F8331) on Android 8.0.0. Cozy Drive v1.10.2 installed from the Play Store.

I do have non-standard folder that I manually added, and was expecting them not to be detected, but the defaults one are still in use, both on the internal memory (`/storage/emulated/0/`) and SD card (`/storage/43D8-1A07/`):

DCIM/100ANDRO/ : Contain whatever pictures or video were taken from the camera, seems to only be used on internal memory.
Pictures: Generic picture folder, the majority of pictures end up there
Movies: Generic video folder
Download: Generic download folder, depending on the method used to get the image (from browser), it may end up there

I'm no android developer, but if need be, I m willing to try out debug builds if it can help

**Comment by Crash--** [comment]
`Sony XPeria`... Hmm. 

I think it's an interesting point since we have other complain from an user using also an XPeria. Let me see how we can handle it. Will come back soon ;)

**Comment by Crash--** [comment]
@D219 can you launch a manual scan and right after send us a comment within the app? We should get some logs

**Comment by D219** [comment]
@Crash-- Done just now, if you need the account name, the domain is `blad`

**Comment by Crash--** [comment]
Thank you @D219. Nothing to exploit though. 

I find out that, some android applications, do not write in `MediaStore` even if there are dealing with photo... 

Can you try, for instance, this application : https://play.google.com/store/apps/details?id=info.superkiki.mediascanner . It seems you can scan a specific folder and add its content to `MediaStore` to see if it works?

**Comment by D219** [comment]
@Crash-- I would have tried, but the permissions asked by the app are unsettling, I will try to find a alternative app and try

**Comment by D219** [comment]
Used this app to try to add to the MediaStore: https://play.google.com/store/apps/details?id=com.house.noranuko.mediarescanner

Nothing got backuped, even after a manual scan, sent feedback to hopefully send more relevant logs.

**Comment by Crash--** [comment]
Thank you @D219 ! Will give a look at your log. 

Next step: I'll create you an APK with added logs. You'll have to install `adb` ;)

**Comment by D219** [comment]
@Crash-- No problem, I ll postpone the switch to lineageOS so that the absence of Google Services don't impede on the test

**Comment by louisgrasset** [comment]
Just to say: I was talking about the windows client. We can't see which file is scanned
