### ISSUE TITLE
infinite loop with file conflict 

### ISSUE THREAD

**Issue by ethicnology** [cozy/cozy-drive#1951]
Hi there,

I'm using Cozy Drive on Ubuntu 18.04.
When i have to edit some file which are sync to the drive it make a conflict (.kdbx file).
Then, we can see the cozy drive infinite looping to create conflict files -> system freeze ->  force shutdown.

**Comment by taratatach** [comment]
Hi @ethicnology.

Thanks for reaching out. This repository is for the Cozy Drive Web application while your problem is with the Cozy Destkop application.
Its repository lives at https://github.com/cozy-labs/cozy-desktop.

I invite you to contact our support via the application itself (`Preferences` tab > `Send us a message`).
This will automatically attach some logs than will help us understand what happened and caused your issue.
You can also caontact us at contact@cozycloud.cc if you prefer.

Have a good day,
Erwan
