### ISSUE TITLE
[Feature Request] Embed password Manager within CozyCloud

### ISSUE THREAD

**Issue by jo-chemla** [cozy/cozy-drive#843]
Hi all, 
A very good use for Cozy Cloud could be embedding a password manager within cozy-cloud - or a way to store buttercup or keepass files, and access them via the master password. Another solution: link buttercup directly to the file stored within cozy cloud, but would require modifying buttercup. 
Jonathan

**Comment by jsilvestre** [comment]
Hi @jo-chemla,

Thank you for the suggestion. I added it to our tracking tool. We are currently not committed to this feature, but it's something people starts asking for so I'm keeping my eyes on it!
As for a password manager app for Cozy, it's also something we are interested in, see this [thread](https://forum.cozy.io/t/gestionnaire-de-mots-de-passe/4406/6) on our forum (french thread) if you'd like to participate.

I'm closing the issue for now, not because it's a no-go, but we use github issues for technical & internal stuff rather than user feedback. Feel free to keep reporting it here if that's what you preferer, I'll save your feedback to our tool so you don't have to worry about our internal way of doing things ;)

Regards,
Joseph.
