### ISSUE TITLE
[mobile] Add Support for iPhone X

### ISSUE THREAD

**Issue by euskadi31** [cozy/cozy-drive#850]

**Comment by jsilvestre** [comment]
Hi @euskadi31 

Thank you for the suggestion. I added it to our tracking tool. That's something we are considering and that will become mandatory in a few months.

I'm closing the issue for now, not because it's a no-go, but we use github issues for technical & internal stuff rather than user feedback. Feel free to keep reporting it here if that's what you preferer, I'll save your feedback to our tool so you don't have to worry about our internal way of doing things ;)

Regards,
Joseph.
